# Generated by Django 3.2.13 on 2022-05-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_voter_votefor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voteFor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.votingoption'),
        ),
    ]
