# Generated by Django 3.2.13 on 2022-05-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220507_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voting',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.voting'),
        ),
    ]
